### ISSUE TITLE
Changing the font results in a blank window.

### ISSUE THREAD

**Issue by Phate6660** [Aloxaf/silicon#104]
I know that it successfullly chooses the font, because inputting an invalid font errors it out stating as such.
It successfullly makes the image, however it is as the title states.

Command used: `silicon projects/github/rsmpc/src/commands/stats.rs -o a/a.png --font "Misc Fixed"`

![image generated](https://i.imgur.com/FjfCeJk.png)

**Comment by Phate6660** [comment]
I got an idea, could the issue be that `Misc Fixed` is a bitmap font? @Aloxaf

**Comment by Phate6660** [comment]
It seems like it: https://github.com/servo/font-kit/issues/127

**Comment by Aloxaf** [comment]
> I got an idea, could the issue be that `Misc Fixed` is a bitmap font? @Aloxaf

Yes, I think that's very possible.
