### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Aloxaf** [Aloxaf/silicon#11]
wating for https://github.com/pcwalton/font-kit/issues/85

**Comment by RazrFalcon** [comment]
With https://github.com/pcwalton/font-kit/pull/92 the app is crashes at:

```
thread 'main' panicked at 'attempt to add with overflow', src\font.rs:281:31
```

**Comment by Aloxaf** [comment]
> With [pcwalton/font-kit#92](https://github.com/pcwalton/font-kit/pull/92) the app is crashes at:
> 
> ```
> thread 'main' panicked at 'attempt to add with overflow', src\font.rs:281:31
> ```

It seems to be a bug on debug mode.
Fixed in 4899038d68c3402dcfbaeb3ab3f4cfa942496eec

**Comment by Aloxaf** [comment]
This issue won't be closed until font-kit publish a new release

**Comment by Gander7** [comment]
`cargo install silicon` failed on Ubuntu WSL (Windows Subsystem)
Error: https://gyazo.com/0d8313a8445d6386c4ffc544816463ce
Is this caused by the same issue, or should I create a new issue?

**Comment by Aloxaf** [comment]
@Gander7 Have you installed freetype?
try `sudo apt install pkg-config libfreetype6-dev libfontconfig1-dev`

**Comment by Gander7** [comment]
Add the following to that list and it worked :)
`sudo apt-get install clang libx11-xcb-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-xfixes0-dev`

Thanks, that font one was throwing me off :)
