### ISSUE TITLE
Please describe how to add support for additional languages

### ISSUE THREAD

**Issue by iensu** [Aloxaf/silicon#122]
First, thank you so much for this, the UX is definitely better than the Carbon CLI tool. 

Currently I'm missing support for WebAssembly Text format and I'm not sure how to add support for it in Silicon.

I noticed that you are pulling syntaxes and themes from the `bat` repository, and support hasn't been added for WebAssembly there yet. However, I was able to locally add support for it in `bat` following their instructions: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions

Is there a way to make silicon use my local `bat` cache, or a way I can add it to the list of assets?

I thought about making a request to `bat` about adding support for WebAssembly, but unfortunately it seems they have a requirement of at least 10000 downloads for the syntax package, which is far from the current number of downloads.

**Comment by Aloxaf** [comment]
Thanks for your report!

Now silicon will also read bat's cache directory.

Please check whether it works

**Comment by iensu** [comment]
Thanks a lot @Aloxaf!

I installed silicon by running `cargo install --git <this repo>`,  but I have some trouble getting it to work on my machine (Darwin Kernel Version 19.6.0).

When invoking silicon like this `silicon src/upper.wat -o upper.png` it fails with `[error] No such file or directory (os error 2)`. I have tried setting both `BAT_CACHE_PATH` and `XDG_CACHE_HOME` respectively, but to no avail. Is it working correctly for you?

**Comment by j0hnmeow** [comment]
Did you build bat cache?

**Comment by iensu** [comment]
@j0hnmeow yes, I built it and I managed to use `bat` with the syntax highlighting. I now tried to specify the master branch during install: `cargo install --git https://github.com/Aloxaf/silicon --branch master`, am I doing it wrong?

**Comment by j0hnmeow** [comment]
Can you send the syntax file and a `wat` example file?

**Comment by iensu** [comment]
Syntax file: https://github.com/bathos/wast-sublime-syntax
Wat example (upper.wat):

```
(module
 (import "env" "memory"
         (memory $mem 1))

 (export "toUpper" (func $toUpper))

 (global $UPPER_OFFSET i32 (i32.const 32))
 (global $LOWERCASE_A i32 (i32.const 97))
 (global $LOWERCASE_Z i32 (i32.const 122))

 (func $toUpper (param $index i32) (param $length i32)
       (local $curChar i32)
       (local $max i32)
       (set_local $max (i32.add (get_local $index) (get_local $length)))

       (loop
        (set_local $curChar (i32.load8_s (get_local $index)))
        (if (call $isLower (get_local $curChar))
            (then (i32.store8 (get_local $index) (i32.sub (get_local $curChar) (get_global $UPPER_OFFSET)))))

        ;; Increment index to handle next byte
        (set_local $index (i32.add (get_local $index) (i32.const 1)))
        ;; Break out of loop after `length' bytes
        (br_if 1 (i32.ge_s (get_local $index) (get_local $max)))

        ;; Break to scope depth of 0, i.e. back to start of loop
        (br 0)))

 (func $isLower (param $char i32) (result i32)
       (i32.and (i32.ge_s (get_local $char) (get_global $LOWERCASE_A))
                (i32.le_s (get_local $char) (get_global $LOWERCASE_Z)))))
```

**Comment by iensu** [comment]
@j0hnmeow I believe I found the issue. The error was trigger by this line: https://github.com/Aloxaf/silicon/blob/master/src/bin.rs#L97, which in the end called this line: https://github.com/Aloxaf/silicon/blob/master/src/config.rs#L219

Here `self.theme` was set to `Dracula`, which I don't have installed and is not listed in the available themes when running `silicon --list-themes`. So the error comes from silicon trying to fetch a non-existing theme. 

If I explicitly specify one of the listed themes like `silicon src/upper.wat --theme GitHub -o upper.png`, then it works.

**Comment by iensu** [comment]
Confirmed this by adding Dracula to the `bat` cache, now everything works with the default theme setting

**Comment by Aloxaf** [comment]
The error message is confusing. I think I should add a context for it.
