### ISSUE TITLE
Allow zero for `--highlight-lines` value

### ISSUE THREAD

**Issue by bkuhlmann** [Aloxaf/silicon#124]
## Overview

Would it be possible to allow zero as a safe value for `--highlight-lines`? Example:

``` bash
silicon --to-clipboard --highlight-lines 0 example.rb
```

Essentially, a value of zero would be like a no-op and as if the `--highlight-lines` option was never used. The reason why this is valuable is for wrapping in a shell script. Without this being possible, the following error happens instead:

``` 
Segmentation fault: 11
```

## Screenshots/Screencasts

Here is an example of a shell script that sets `--highlight-lines` to zero as a default option which will fail with the above mentioned error. It would be nice to allow zero in this situation.

![image](https://user-images.githubusercontent.com/50245/98190416-34a41280-1ed4-11eb-98a4-d6aedfec31ea.png)

## Steps to Recreate

``` 
touch example.rb
silicon --to-clipboard --highlight-lines 0 example.rb
```

## Desired Behavior

Don't throw a segfault and ignore `--highlight-lines` instead since it's a no-op.

**Comment by Aloxaf** [comment]
I test it but didn't get a segfault. But the result is strange, I should indeed ignore line 0.

![image](https://user-images.githubusercontent.com/17017672/98191866-12060e00-1f55-11eb-97bb-85de32d4c393.png)

**Comment by bkuhlmann** [comment]
Yeah, strange you don't see the segfault. If it helps, here is some extra diagnostic info:

``` 
silicon --version
silicon 0.3.2

Operating System
macOS (10.15.6 (19G2021)), x86_64-darwin19
```

**Comment by bkuhlmann** [comment]
Hey @Aloxaf, will you be releasing a new Homebrew version with the above fix soon? I'd love to pick up this fix if possible. :wink:

**Comment by Aloxaf** [comment]
Ok. I will make a release soon.

**Comment by bkuhlmann** [comment]
Awesome, thanks and thanks for the fix too!
