### ISSUE TITLE
Disadvantages

### ISSUE THREAD

**Issue by j0hnmeow** [Aloxaf/silicon#129]
The [Disadvantages](https://github.com/Aloxaf/silicon#disadvantages) section says it's not as beautiful, is there a kind of image comparison?

**Comment by Aloxaf** [comment]
In fact, this depends on theme. I think I can remove this since Dracula is good enough.

**Comment by j0hnmeow** [comment]
So "not as beautiful" just means different syntax highlighting?

**Comment by Aloxaf** [comment]
Yes
