### ISSUE TITLE
v0.4.0 tarball sha256 change?

### ISSUE THREAD

**Issue by carlocab** [Aloxaf/silicon#141]
I'm attempting to update Homebrew's version of Rust (https://github.com/Homebrew/homebrew-core/pull/66285).

While testing the new version, CI produced the following error:
```
==> brew install --build-from-source silicon
==> FAILED
==> Downloading https://github.com/Aloxaf/silicon/archive/v0.4.0.tar.gz
==> Downloading from https://codeload.github.com/Aloxaf/silicon/tar.gz/v0.4.0
Error: SHA256 mismatch
Expected: 1534b7b4b5a309cf7f79132f3cd5fd7987642735ca7845efb1ec93df685a402d
  Actual: 423c03d9c92cbad8f5a136abaa680e85dfa5b5f31998aab4424c335d4d99b7ab
```

I can update the sha256 associated with silicon, but CI will come back to me with the following error:
```
silicon:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

Can I confirm that nothing is amiss here?

**Comment by Aloxaf** [comment]
Oh, sorry about that.

I think this is because I moved CI from Travis to GitHub action in https://github.com/Aloxaf/silicon/commit/b6b0d8fab66caaa901a659d2953083cf43ce63ab and retag 0.4.0 to trigger release action.

**Comment by carlocab** [comment]
Thanks. I'll report this back to Homebrew and close this issue when the sha256 fix PR is merged.

**Comment by carlocab** [comment]
PR merged. Thanks again!
