### ISSUE TITLE
v0.4.0 tarball for linux is not compressed by xz

### ISSUE THREAD

**Issue by gamoutatsumi** [Aloxaf/silicon#142]
Downloaded silicon-v0.4.0-x86_64-unknown-linux-gnu.tar.xz from GitHub Release, but that seems to be compressed by Gzip.

Shouldn't this file compressed by xz?

I checked by `file` command:

```bash
$ file silicon-v0.4.0-x86_64-unknown-linux-gnu.tar.xz
silicon-v0.4.0-x86_64-unknown-linux-gnu.tar.xz: gzip compressed data, last modified: Tue Dec  1 04:17:45 2020, from Unix, original size modulo 2^32 8755200
```

**Comment by Aloxaf** [comment]
Oh, sorry about that.
It is a mistake.
