### ISSUE TITLE
Silicon 0.4.0 on Big Sur generates empty window frames without text

### ISSUE THREAD

**Issue by berkus** [Aloxaf/silicon#147]
![image](https://user-images.githubusercontent.com/80306/103171755-65128800-4857-11eb-82da-6473a1e81943.png)

I installed it using `cargo install silicon` after the latest pasteboard fixes were applied.

I tried adding text via clipboard contents, from file and by entering it directly from stdin. In all cases the output image seems to be sized appropriate to amount of entered text, but the text itself is not visible.

I wonder if this is a problem with fonts or themes, `--list-themes` as well as `--list-fonts` output non-empty lists. I've tried both default theme and font and custom theme (zenburn) and a fallback font (Hack).

**Comment by Aloxaf** [comment]
Does font-kit's example work well?

```zsh
git clone https://github.com/servo/font-kit
cd font-kit
cargo run --example render-glyph -- FONT_NAME 'A'
```

**Comment by berkus** [comment]
Seems like not, it only prints `glyph 36:` but not the glyph itself. Any hints?

**Comment by Aloxaf** [comment]
Seems to be the bug of font-kit. I have no macOS device, you can submit an issue to font-kit's repo.

**Comment by berkus** [comment]
Alright, I'll check it with them, thank you!

**Comment by berkus** [comment]
I traced this to simd implementation errors in [pathfinder_simd](https://github.com/servo/pathfinder/issues/450) crate.

**Comment by berkus** [comment]
Proposed fix https://github.com/servo/pathfinder/pull/452

**Comment by berkus** [comment]
With the fix applied everything looks fine now:

![image](https://user-images.githubusercontent.com/80306/104136372-53c09400-539e-11eb-941a-e379ec9c61da.png)

**Comment by Aloxaf** [comment]
Amazing work! Now we just need to wait for the new release of pathfinder.

**Comment by berkus** [comment]
And servo/font-kit of which i'm more concerned - they seem inactive.

**Comment by berkus** [comment]
Hi! JFYI:

pathfinder_simd has released a [new version](https://lib.rs/crates/pathfinder_simd) with the fix recently, font-kit seems dead but they use a `="0.5"` dependency in their Cargo.toml so it should pick up the latest version automatically.

I'll run cargo install on my machine and see if this is now building fine.

**Comment by berkus** [comment]
🕺🏼
