### ISSUE TITLE
Add Apple Silicon Homebrew missing formula

### ISSUE THREAD

**Issue by bkuhlmann** [Aloxaf/silicon#156]
## Overview

Would it be possible to add a Homebrew formula for Apple Silcon machines?

## Steps to Recreate

On a Apple Silicon machine, try running:

``` 
brew install silicon
```

You'll then get the following error:

``` 
Warning: Treating silicon as a formula. For the cask, use homebrew/cask/silicon
Error: silicon: no bottle available!
```

## Desired Behavior

Would be nice to install Silicon via Homebrew without error.

## Environment

macOS 11.2.1 (20D75)
MacBook Air (M1, 2020)

**Comment by Aloxaf** [comment]
Sorry, I am not familiar with homebrew. But it seems that there is already a formula? https://github.com/Homebrew/homebrew-core/blob/master/Formula/silicon.rb

**Comment by bkuhlmann** [comment]
:bow: Aloxof. Yeah, there is a formula but looks like it has to be updated there. OK, I'll close this and follow up there. :wink:

**Comment by bkuhlmann** [comment]
Hey Aloxof. :wave: I posted this [Homebrew Issue](https://github.com/Homebrew/homebrew-core/issues/72168#issuecomment-787482351) but they defered back to this project as Silicon would need to be build for Apple Silicon machines in order to support the install process. Would that be hard to do?

**Comment by Aloxaf** [comment]
Oh, it seems that I need to update Cargo.lock: https://github.com/Homebrew/homebrew-core/issues/68301. Thanks for your information!

I just updated it. You can check if you can install silicon with `cargo install --git https://github.com/Aloxaf/silicon.git` now. If it succeeds, I will make a new release and then you could make a PR to update to formula.

**Comment by bkuhlmann** [comment]
:bow: Aloxaf. Confirmed, yep, that works!

**Comment by Aloxaf** [comment]
Good. Now 0.4.1 is relased.

**Comment by bkuhlmann** [comment]
🙇 Aloxaf. I'll close this and wait for further action via the Homebrew issue.
