### ISSUE TITLE
Latest update is failing to compile

### ISSUE THREAD

**Issue by augustocdias** [Aloxaf/silicon#158]
Installing through cargo install.

```
   Compiling pasteboard v0.1.2
error[E0308]: mismatched types
  --> /Users/augusto/.cargo/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:75:12
   |
75 |         if ok {
   |            ^^ expected `bool`, found `i8`

error[E0308]: mismatched types
  --> /Users/augusto/.cargo/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:82:59
   |
82 |             NSData::writeToFile_atomically_(object, path, false);
   |                                                           ^^^^^ expected `i8`, found `bool`

error: aborting due to 2 previous errors
```

**Comment by Aloxaf** [comment]
Are you using Big Sur?

**Comment by augustocdias** [comment]
Yes I am @Aloxaf

**Comment by segeljakt** [comment]
Which version of big sur are you running?

**Comment by augustocdias** [comment]
11.2.2

**Comment by Aloxaf** [comment]
@segeljakt It seems that not all Big Sur run on arm device.

Replacing custom `big_sur_update` with `target_arch = "aarch64"` may be a better choice? 

ref. https://github.com/SSheldon/rust-objc/blob/master/src/runtime.rs#L27-L28

**Comment by segeljakt** [comment]
Ok, interesting, I can upload a patch later today

**Comment by augustocdias** [comment]
Any update on this?

**Comment by chenrui333** [comment]
Any update on this (as it does impact on the silicon 0.4.1 build)?

**Comment by Aloxaf** [comment]
@chenrui333 I dropped the clipboard support on macOS arm. Now it should be able to be built on Big Sur.

**Comment by mikemadden42** [comment]
I see this same issue.

```
$ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)

$ sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```

```
error[E0308]: mismatched types
  --> /Users/mjm/.cargo/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:75:12
   |
75 |         if ok {
   |            ^^ expected `bool`, found `i8`

error[E0308]: mismatched types
  --> /Users/mjm/.cargo/registry/src/github.com-1ecc6299db9ec823/pasteboard-0.1.2/src/lib.rs:82:59
   |
82 |             NSData::writeToFile_atomically_(object, path, false);
   |                                                           ^^^^^ expected `i8`, found `bool`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `pasteboard`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Aloxaf** [comment]
@mikemadden42 Can git version be compiled?

**Comment by segeljakt** [comment]
Apologies for the long wait. I pushed an update to pasteboard which should hopefully fix this issue. If not then please report back. It works for me now on `macOS 11.4.0`.

**Comment by mikemadden42** [comment]
Thanks @segeljakt .  Updating to `pasteboard v0.1.3` fixed the build issue I was seeing on macOS Big Sur.

**Comment by mikemadden42** [comment]
@segeljakt @Aloxaf Do you think we should update this version of `pasteboard` in master so this builds cleanly on macOS Big Sur?

https://github.com/Aloxaf/silicon/blob/master/Cargo.toml#L25

**Comment by Aloxaf** [comment]
@segeljakt Thanks!

@mikemadden42 Done!

**Comment by chenrui333** [comment]
I can confirm [this commit](https://github.com/Aloxaf/silicon/commit/e7d6955061f4167b44620fc7463f60d77dd69e0b) fixed the build issue, and we have made the upgrade in the homebrew-core side
