### ISSUE TITLE
Feature request: Window titles

### ISSUE THREAD

**Issue by gapan** [Aloxaf/silicon#180]
I think it would be nice if there was a way to add an (optional) window title next to the window controls.

**Comment by harrisoncramer** [comment]
This would be hugely helpful. I'm trying to use this to share screenshots of specific files at work and having the filename baked into the title would be great

**Comment by mrcoalp** [comment]
Hey @Aloxaf :wave: 

I've created a PR adding this feature. Take a look at it, if you have the chance. First time trying Rust, though...
