### ISSUE TITLE
NeoVim package silicon.lua

### ISSUE THREAD

**Issue by NarutoXY** [Aloxaf/silicon#212]
Hi!

I found silicon so useful so I wrote a simple nvim plug-in for it:
https://github.com/narutoxy/silicon.lua

**Comment by ilias777** [comment]
I tried both, `silicon.lua` for Neovim and `silicon cli` in the terminal  and they are awesome.
I am on Mac and unfortunately I can't use `silicon.lua` because the version 0.5.1 is required and in homebrew is the silicon version on 0.4.3.

So if it's possible please @Aloxaf upgrade in homebrew the latest version. 
Thank you very much for this amazing tool 😊

**Comment by zanglg** [comment]
Got the same issue, Mac's silicon version was not up to date.

**Comment by NarutoXY** [comment]
You can actually use older versions
You need to do something like
```lua
require("silicon").setup({theme="Dracula"})
```

By default the plug-in uses the new functionality of 0.5.1 to create themes matching editor theme

**Comment by ilias777** [comment]
Yes it works now with `theme = 'Dracula'`

Unfortunately it not exist a command like `:Silicon` and I have to copy and paste the lua code every time in the command line to generate the screenshots.
But it works! Thx 😊

**Comment by NarutoXY** [comment]
You can actually first select code in visual mode then use the command given in README of project in the meantime.

**Comment by Aloxaf** [comment]
Seems good, added to related projects.

**Comment by Aloxaf** [comment]
> I tried both, `silicon.lua` for Neovim and `silicon cli` in the terminal and they are awesome. I am on Mac and unfortunately I can't use `silicon.lua` because the version 0.5.1 is required and in homebrew is the silicon version on 0.4.3.
> 
> So if it's possible please @Aloxaf upgrade in homebrew the latest version. Thank you very much for this amazing tool blush

I'd like to. But homebrew package is not matained by me.

**Comment by heygarrett** [comment]
The homebrew package has been updated:  
https://github.com/Homebrew/homebrew-core/pull/114853

**Comment by NarutoXY** [comment]
> Seems good, added to related projects.

Thanks. Closing this issue then. 

Thanks again for the awesome tool.
