### ISSUE TITLE
Add to AUR

### ISSUE THREAD

**Issue by gunar** [Aloxaf/silicon#22]
Would you care to add it to the AUR package repository?

Love the idea!

**Comment by radmen** [comment]
@gunar actually... I did this :) https://aur.archlinux.org/packages/silicon

**Comment by Aloxaf** [comment]
@radmen Thank you, I will add it to the README later.

**Comment by Aloxaf** [comment]
@radmen I failed to install it. You may forget to add `0001-font-kit.patch`.

BTW. `xclip fontconfig freetype2` is required for silicon.

**Comment by radmen** [comment]
@Aloxaf thanks for info. Patch is [applied in PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=silicon#n24)

I'll add missing dependencies. As I understand `xclip` is an optional dependency, required to work with system clipboard?

**Comment by radmen** [comment]
Could you leave me a log from the build?

**Comment by radmen** [comment]
> You may forget to add 0001-font-kit.patch.

aye, it was on ignore list :man_facepalming: 

> BTW. xclip fontconfig freetype2 is required for silicon.

Added all of them.

Package got update. Will you give it another spin? Thank you!

**Comment by Aloxaf** [comment]
@radmen You can use `namcap` to analyze the package. It still seems to miss custom license directory (https://wiki.archlinux.org/index.php/PKGBUILD#license). But it can be installed successfully now~

**Comment by radmen** [comment]
@Aloxaf Thank you. I've added missing LICENSE

**Comment by radmen** [comment]
@Aloxaf FYI 0.2.6 has been released. I think that this issue can be closed :) Thank you!

**Comment by Aloxaf** [comment]
@radmen Thank you, too :)
