### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by mys721tx** [Aloxaf/silicon#23]
Currently, all transparency are hardcoded to `0xff`:

https://github.com/Aloxaf/silicon/blob/c277f1a21f5fa687183599e3a6802435917e2ef9/src/utils.rs#L27-L32

There should be a switch to toggle the background transparency so that the output image can be readily used without concerns of background color.

I can think of are two way to implement this:

1. Change the RGBA parsing so that the alpha will also be parsed. This may involves extra handling of RGB string. This may allow transparent theme in the future.
2. Create a new boolean argument so that it will override the alpha setting in `Config.background`. This likely will involve some processing outside of the struct declaration.

I would like to invite comments from everyone for how to proceed.

**Comment by Aloxaf** [comment]
I'd like to choose the first way. But I'm not sure whether it will affect the other function of silicon. Silicon should have some tests.

BTW, the transparent theme is already supported (if there are)
https://github.com/Aloxaf/silicon/blob/4ea9203602bef74b5c58de0b8aca44f2185494e4/src/utils.rs#L36-L41

**Comment by AndydeCleyre** [comment]
> BTW, the transparent theme is already supported (if there are)

As in, it's possible to have a theme where the fake window is transparent, revealing the image background behind?

Are there any known themes which do this?
