### ISSUE TITLE
`cargo install silicon` fails

### ISSUE THREAD

**Issue by salopst** [Aloxaf/silicon#243]
> error: linking with `cc` failed: exit status: 1

`cc` (and `ld`) are located at /usr/bin/

Pop!_0S 22.04  
rustup 1.26.0 (5af9b9484 2023-04-05)  
rustc 1.76.0 (07dca489a 2024-02-04)

**Comment by RemasteredArch** [comment]
As far as I'm aware, the Ubuntu install instructions are missing some packages (see #244). Try installing `g++`:
```sudo apt install g++```
