### ISSUE TITLE
Versions release

### ISSUE THREAD

**Issue by radmen** [Aloxaf/silicon#25]
Hey!

I've just pushed an AUR package of this awesome app (https://aur.archlinux.org/packages/silicon).

During the process of building this package I had one problem - there are no tags or releases (which basically are tags) for the versions of the application. I have to find a commit which was version bump and then use it in the package build process.

Would it be possible to start using GH release feature? It will help me keeping package up-to-date in the AUR repository.

Thanks!

**Comment by Aloxaf** [comment]
Thanks for your advice!

I will start using it in next release

**Comment by Aloxaf** [comment]
[0.2.6](https://github.com/Aloxaf/silicon/releases/tag/v0.2.6) has been released, you can upadte the AUR package now~

**Comment by radmen** [comment]
Thank you!
