### ISSUE TITLE
tabs vs spaces

### ISSUE THREAD

**Issue by dbarrosop** [Aloxaf/silicon#28]
Hello,
awesome tool :) I did some tests with python and golang code and looks like silicon doesn't like tabs as it removes them rendering all the text aligned to the left (golang forces you to use tabs). Worked fine with python and spaces.

Regards
David

**Comment by Aloxaf** [comment]
Thanks for reporting it : )

Now it has been fixed and you can use `--tab-width` to control the tab width

**Comment by dbarrosop** [comment]
Awesome, just tested it and I can confirm it works beautifully.

Thanks! :D
