### ISSUE TITLE
Encoding in windows

### ISSUE THREAD

**Issue by zxj5470** [Aloxaf/silicon#86]
![image](https://user-images.githubusercontent.com/20026798/83274677-a4fd8800-a200-11ea-8cf6-916ede2bbbd9.png)

**Comment by zxj5470** [comment]
```cpp
#include <iostream>
// 你好世界
// 안녕하세요
```

**Comment by zxj5470** [comment]
If I change the default font into YaHeiMonacoHybrid，I'll see
![a](https://user-images.githubusercontent.com/20026798/83275415-b2674200-a201-11ea-83ce-df001e835970.png)

**Comment by zxj5470** [comment]
Can I get all available FontNames ？

**Comment by Aloxaf** [comment]
Sorry for the late replHow about `-f "Hack; simsun; consolas"` ?

**Comment by zxj5470** [comment]
OK.
